Migrated labels to Vue
TicketVise/ticketvise pull request #326
Opened 2020-10-24 17:14 UTC by tomwassing

2020-10-25 14:56 UTC, rubenjonk requested changes

2020-10-25 14:56 UTC, rubenjonk commented on frontend/components/inbox/Label.vue
> +        color: '#' + Math.random().toString(16).substr(2, 6),
We hebben een set aan standaard kleuren waar we overheen kunnen lopen, dat helpt om zo geen vage of te felle kleuren te krijgen

2020-10-25 14:56 UTC, rubenjonk commented on frontend/components/inbox/Label.vue
> +          history.back()
Wordt een label wel in de lijst gezet als er een history.back aangeroepen wordt?

2020-11-01 21:54 UTC, IvandeWolf approved these changes
Ziet er goed uit!

2020-11-02 08:51 UTC, merged